### ISSUE TITLE
crash on `reflow shell`

### ISSUE THREAD

**Issue by ryanking** [grailbio/reflow#17]
```
$ reflow shell ec2-52-89-134-253.us-west-2.compute.amazonaws.com:9000/37053975f9eb8ae1/37cadd2ce6679c19c930b58fc99adb750963cb82d720f24e6efd434566829a79
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1071c72]

goroutine 1 [running]:
io.copyBuffer(0x2067900, 0xc42000e018, 0x0, 0x0, 0xc420274000, 0x8000, 0x8000, 0xc42045baa0, 0xc42045ba90, 0x17b0e40)
	/Users/marius/.gimme/versions/go1.9.1.darwin.amd64/src/io/io.go:392 +0x102
io.Copy(0x2067900, 0xc42000e018, 0x0, 0x0, 0x0, 0x20666c0, 0xc4204b4380)
	/Users/marius/.gimme/versions/go1.9.1.darwin.amd64/src/io/io.go:362 +0x68
github.com/grailbio/reflow/tool.(*Cmd).shell(0xc42037e000, 0x206ea00, 0xc420018088, 0xc4200100e0, 0x1, 0x1)
	/Users/marius/go/src/github.com/grailbio/reflow/tool/shell.go:58 +0x6da
github.com/grailbio/reflow/tool.(*Cmd).Main(0xc42037e000)
	/Users/marius/go/src/github.com/grailbio/reflow/tool/main.go:249 +0x56b
main.main()
	/Users/marius/go/src/github.com/grailbio/reflow/cmd/reflow/main.go:63 +0x3b1
```

**Comment by prasadgopal** [comment]
Fixed in [commit](https://github.com/grailbio/reflow/commit/20e84b648bbdfc5e54a78027bbcc530afa16e059)
